import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import fs from "node:fs";
import { prisma } from "../../src/lib/prisma";
import { changeCupEntry, getCupInvitationReport, getCupResponseContext, previewCupInvitations, respondToCup, saveCupInvitationSettings, sendCupInvitations } from "../../src/lib/cups/invitations";
import { loadCup, loadInvitation } from "../../src/lib/cups/invitation-data";
import { cupInvitationDeliveryBlock } from "../../src/lib/cups/invitation-delivery";
import { cupResponseToken } from "../../src/lib/cups/invitation-policy";
const url=new URL(process.env.DATABASE_URL!);
assert.equal(process.env.CUP_TEST_DATABASE,"1");assert.ok(["localhost","127.0.0.1"].includes(url.hostname));assert.equal(url.pathname,"/sixfl_cup_invitation_test");
globalThis.fetch=async()=>{throw Error("No external request or delivery is permitted by cup tests");};
async function main(){
 const admin=await prisma.user.create({data:{name:"Cup administrator",role:"ADMIN",email:"cup-admin@example.invalid"}});
 const outsider=await prisma.user.create({data:{name:"Other player",email:"outsider@example.invalid"}});
 const league=await prisma.league.create({data:{name:"Normal league",slug:"normal-test",season:"Test",leagueType:"MENS"}});
 const wrong=await prisma.league.create({data:{name:"Different category",slug:"different-test",season:"Test",leagueType:"WOMENS"}});
 const comp=await prisma.leagueCompetition.create({data:{name:"SIXFL County Cup",slug:"county-test",leagueType:"MENS",competitionType:"CUP",cupFormat:"KNOCKOUT",isInterLeague:true}});
 const cup=await prisma.league.create({data:{name:comp.name,slug:"county-season-test",season:"Test",competitionId:comp.id,leagueType:"MENS"}});
 await prisma.leagueCompetition.update({where:{id:comp.id},data:{currentLeagueId:cup.id}});
 async function team(name:string,opts:{placeholder?:boolean;members?:boolean;noEmail?:boolean;leagueId?:string}={}){
  const id=randomUUID();const user=await prisma.user.create({data:{name:`${name} Captain`,email:`${id}@example.invalid`}});
  const t=await prisma.team.create({data:{name,claimCode:id,leagueId:opts.leagueId||league.id,contactName:`${name} Contact`,contactEmail:opts.noEmail?null:user.email}});
  if(opts.placeholder)await prisma.$executeRaw`UPDATE "Team" SET "isFixturePlaceholder"=true WHERE id=${t.id}`;
  if(opts.members!==false)await prisma.$executeRaw`INSERT INTO "LeagueSeasonTeam" (id,"leagueId","teamId") VALUES (${randomUUID()},${opts.leagueId||league.id},${t.id})`;
  if(!opts.noEmail)await prisma.teamMember.create({data:{teamId:t.id,userId:user.id,role:"CAPTAIN"}});
  return {...t,captain:user};
 }
 const a=await team("Alpha"),b=await team("Beta"),c=await team("Gamma"),d=await team("Delta"),silent=await team("No email",{noEmail:true});
 const placeholder=await team("Fixture placeholder",{placeholder:true});const affiliate=await team("Affiliated only",{members:false});const category=await team("Wrong category",{leagueId:wrong.id});
 const extra=await prisma.user.create({data:{name:"Additional Captain",email:"additional@example.invalid"}});
 await prisma.teamMember.create({data:{teamId:a.id,userId:extra.id,role:"CAPTAIN"}});
 const base={cupId:cup.id,actorId:admin.id,expectedVersion:0,fee:"40",venueNote:"Rawdon and Catterick — proposed, subject to confirmation.",scheduleNote:"May be a different night. Dates and kick-off times to be confirmed.",deadlineDate:new Date(Date.now()+28*86400000).toISOString().slice(0,10),deadlineTime:"18:00",state:"OPEN"};
 const dispatchCount=()=>prisma.notificationDispatch.count();
 const cupEntries=()=>prisma.$queryRaw`SELECT * FROM "LeagueSeasonTeam" WHERE "leagueId"=${cup.id}`;
 await assert.rejects(saveCupInvitationSettings({...base,actorId:outsider.id}));
 await saveCupInvitationSettings(base);const originalDeadline=(await loadCup(cup.id)).settings!.responseDeadline;assert.equal(await dispatchCount(),0);
 const report=await getCupInvitationReport(cup.id,admin.id);
 assert.equal(report.rows.length,5);for(const t of [placeholder,affiliate,category])assert.ok(!report.rows.some(r=>r.id===t.id));
 assert.equal(report.rows.find(t=>t.id===a.id)?.contacts.length,2,"same primary/captain email deduped, extra captain retained");
 assert.equal(report.rows.find(t=>t.id===silent.id)?.deliveryProblem,true);
 const baseline=await prisma.$queryRaw`SELECT to_jsonb(t) AS row FROM "Team" t ORDER BY id`;
 const primaryBefore=await prisma.$queryRaw`SELECT to_jsonb(u) AS row FROM "User" u ORDER BY id`;
 const preview=await previewCupInvitations({cupId:cup.id,actorId:admin.id,teamIds:[a.id,b.id],kind:"INITIAL"});
 assert.match(preview.teams[0].previews[0].bodyText,/£40/);assert.match(preview.teams[0].previews[0].bodyHtml!,/subject to confirmation/);
 assert.match(preview.teams[0].previews[0].bodyHtml!,/Yes — our team is interested/);assert.equal(await dispatchCount(),0);
 const sendInput={cupId:cup.id,actorId:admin.id,teamIds:[a.id,b.id],kind:"INITIAL" as const,previewKey:preview.previewKey,confirmed:true};
 await assert.rejects(sendCupInvitations({...sendInput,confirmed:false}));
 const sent=await Promise.all([sendCupInvitations(sendInput),sendCupInvitations(sendInput)]);
 assert.ok(sent.flat().every(r=>!r.error),JSON.stringify(sent));assert.equal(await dispatchCount(),3);
 assert.equal((await prisma.$queryRaw<Array<{n:number}>>`SELECT COUNT(*)::int AS n FROM "CupInvitation"`)[0].n,2);
 const messages=await prisma.$queryRaw<Array<{id:string;dispatchId:string;recipientEmail:string;recipientName:string;teamId:string}>>`SELECT m.*,i."teamId" FROM "CupInvitationMessage" m JOIN "CupInvitation" i ON i.id=m."invitationId" ORDER BY m.id`;
 const one=messages.find(m=>m.teamId===a.id)!;const initial=await prisma.notificationDispatch.findUniqueOrThrow({where:{id:one.dispatchId},include:{recipient:true}});
 assert.equal(initial.status,"QUEUED");assert.match(initial.bodyText,/not a final entry/);assert.doesNotMatch(initial.bodyText,/cup-admin|outsider/);
 const token=cupResponseToken(one.id,originalDeadline);
 const context=await getCupResponseContext({token});assert.equal(context.team.id,a.id);assert.equal(context.canRespond,true);
 assert.equal((await loadInvitation(cup.id,a.id))?.response,"PENDING");assert.equal(await dispatchCount(),3);
 assert.deepEqual(await prisma.$queryRaw`SELECT to_jsonb(t) AS row FROM "Team" t ORDER BY id`,baseline);
 assert.deepEqual(await prisma.$queryRaw`SELECT to_jsonb(u) AS row FROM "User" u ORDER BY id`,primaryBefore,"previews and signed GET checks cannot sync user phone data");
 assert.equal(await cupInvitationDeliveryBlock(initial),null);
 await assert.rejects(getCupResponseContext({cupId:cup.id,teamId:a.id,actorId:b.captain.id}));
 await assert.rejects(respondToCup({access:{token},response:"YES",expectedVersion:0,confirmed:false}));
 const choices=await Promise.allSettled([respondToCup({access:{token},response:"YES",expectedVersion:0,confirmed:true}),respondToCup({access:{cupId:cup.id,teamId:a.id,actorId:extra.id},response:"NO",expectedVersion:0,confirmed:true})]);
 assert.equal(choices.filter(r=>r.status==="fulfilled").length,1,"stale competing captain choice must be rejected");
 const first=await loadInvitation(cup.id,a.id);assert.equal(first?.responseVersion,1);
 if(first?.response!=="YES")await respondToCup({access:{token},response:"YES",expectedVersion:1,confirmed:true});
 assert.equal((await cupEntries() as unknown[]).length,0,"interest cannot add cup membership");
 assert.ok(await cupInvitationDeliveryBlock(initial));
 assert.equal((await prisma.notificationDispatch.findUniqueOrThrow({where:{id:one.dispatchId}})).status,"CANCELLED");
 const noMessage=messages.find(m=>m.teamId===b.id)!;
 await respondToCup({access:{token:cupResponseToken(noMessage.id,originalDeadline)},response:"NO",expectedVersion:0,confirmed:true});
 assert.equal((await previewCupInvitations({cupId:cup.id,actorId:admin.id,teamIds:[a.id,b.id],kind:"REMINDER"})).teams.filter(t=>!!t.error).length,2);
 const counts=(await getCupInvitationReport(cup.id,admin.id)).counts;assert.equal(counts.yes,1);assert.equal(counts.no,1);assert.equal(counts.problems,1,"cancelled emails after responses are not delivery failures");
 console.log("PASS real templates, preview-only reads, all captains, duplicate sends, safe GET, isolation and concurrent responses");
 // Closing/reopening the same terms never loses replies. Material changes mark them outdated.
 await saveCupInvitationSettings({...base,expectedVersion:1,state:"CLOSED"});assert.equal((await loadCup(cup.id)).settings?.version,1);assert.equal((await getCupInvitationReport(cup.id,admin.id)).counts.yes,1);
 assert.equal((await getCupResponseContext({token})).canRespond,false);
 await saveCupInvitationSettings({...base,expectedVersion:2});assert.equal((await loadCup(cup.id)).settings?.version,1);
 await saveCupInvitationSettings({...base,expectedVersion:3,venueNote:"Rawdon — proposed; dates still to be agreed."});
 assert.equal((await getCupInvitationReport(cup.id,admin.id)).counts.outdated,2);assert.equal((await getCupResponseContext({token})).canRespond,false);
 const revision=(await loadCup(cup.id)).settings!;
 // Contact change, suppression, channel preferences, and disabled templates stay authoritative.
 const cRecipient=await prisma.notificationRecipient.create({data:{sourceType:"TEAM",sourceId:c.id,audience:"TEAM",email:c.contactEmail,emailNormalized:c.contactEmail,isSuppressed:true}});
 await prisma.notificationPreference.create({data:{recipientId:cRecipient.id,emailEnabled:false}});
 const cp=await previewCupInvitations({cupId:cup.id,actorId:admin.id,teamIds:[c.id],kind:"INITIAL"});
 const cr=await sendCupInvitations({...sendInput,teamIds:[c.id],previewKey:cp.previewKey});assert.equal(cr[0].skipped,1);
 assert.equal((await prisma.notificationRecipient.findUniqueOrThrow({where:{id:cRecipient.id}})).isSuppressed,true);
 assert.equal((await prisma.notificationPreference.findUniqueOrThrow({where:{recipientId:cRecipient.id}})).emailEnabled,false);
 const dp=await previewCupInvitations({cupId:cup.id,actorId:admin.id,teamIds:[d.id],kind:"INITIAL"});
 await prisma.team.update({where:{id:d.id},data:{contactEmail:"changed@example.invalid"}});
 await assert.rejects(sendCupInvitations({...sendInput,teamIds:[d.id],previewKey:dp.previewKey}),/changed/);
 const dp2=await previewCupInvitations({cupId:cup.id,actorId:admin.id,teamIds:[d.id],kind:"INITIAL"});await sendCupInvitations({...sendInput,teamIds:[d.id],previewKey:dp2.previewKey});
 const dms=await prisma.$queryRaw<Array<{id:string;dispatchId:string;recipientEmail:string}>>`SELECT m.* FROM "CupInvitationMessage" m JOIN "CupInvitation" i ON i.id=m."invitationId" WHERE i."teamId"=${d.id}`;
 const dm=dms.find(m=>m.recipientEmail==="changed@example.invalid")!,dd=await prisma.notificationDispatch.findUniqueOrThrow({where:{id:dm.dispatchId}});
 await prisma.team.update({where:{id:d.id},data:{contactEmail:"changed-again@example.invalid"}});
 assert.ok(await cupInvitationDeliveryBlock(dd));await assert.rejects(getCupResponseContext({token:cupResponseToken(dm.id,revision.responseDeadline)}),/current team contact/);
 await prisma.notificationTemplate.update({where:{key:"cup-interest-invitation"},data:{isActive:false}});
 await assert.rejects(previewCupInvitations({cupId:cup.id,actorId:admin.id,teamIds:[a.id],kind:"INITIAL"}),/Enable/);
 await prisma.notificationTemplate.update({where:{key:"cup-interest-invitation"},data:{isActive:true}});
 console.log("PASS closed/reopened/material revisions, missing contacts, suppression, opt-out, disabled templates and revoked contacts");
 // Reminders use the real queue and stop after any response, including manual retries.
 const e=await team("Reminder team"),ep=await previewCupInvitations({cupId:cup.id,actorId:admin.id,teamIds:[e.id],kind:"INITIAL"});await sendCupInvitations({...sendInput,teamIds:[e.id],previewKey:ep.previewKey});
 let rp=await previewCupInvitations({cupId:cup.id,actorId:admin.id,teamIds:[e.id],kind:"REMINDER"});assert.ok(rp.teams[0].error);
 await prisma.$executeRaw`UPDATE "NotificationDispatch" SET status='SENT',"sentAt"=NOW() WHERE id IN (SELECT m."dispatchId" FROM "CupInvitationMessage" m JOIN "CupInvitation" i ON i.id=m."invitationId" WHERE i."teamId"=${e.id})`;
 rp=await previewCupInvitations({cupId:cup.id,actorId:admin.id,teamIds:[e.id],kind:"REMINDER"});assert.equal(rp.teams[0].error,null);
 const rr=await sendCupInvitations({...sendInput,teamIds:[e.id],kind:"REMINDER",previewKey:rp.previewKey});assert.equal(rr[0].queued,1);
 assert.ok((await previewCupInvitations({cupId:cup.id,actorId:admin.id,teamIds:[e.id],kind:"REMINDER"})).teams[0].error);
 const reminder=(await prisma.$queryRaw<Array<{dispatchId:string}>>`SELECT m."dispatchId" FROM "CupInvitationMessage" m JOIN "CupInvitation" i ON i.id=m."invitationId" WHERE i."teamId"=${e.id} AND m.kind='REMINDER'`)[0];
 const rd=await prisma.notificationDispatch.findUniqueOrThrow({where:{id:reminder.dispatchId}});
 await respondToCup({access:{cupId:cup.id,teamId:e.id,actorId:e.captain.id},response:"NO",expectedVersion:0,confirmed:true});assert.ok(await cupInvitationDeliveryBlock(rd));
 // Confirmed entries are explicit and ordinary league membership and fees stay unchanged.
 const beforeCharges=await prisma.paymentCharge.count();
 await assert.rejects(changeCupEntry({cupId:cup.id,teamId:a.id,actorId:outsider.id,remove:false,confirmed:true}));
 await changeCupEntry({cupId:cup.id,teamId:a.id,actorId:admin.id,remove:false,confirmed:true});
 assert.equal((await prisma.team.findUniqueOrThrow({where:{id:a.id}})).leagueId,league.id);assert.equal(await prisma.paymentCharge.count(),beforeCharges);
 const f=await prisma.fixture.create({data:{leagueId:cup.id,homeTeamId:a.id,awayTeamId:b.id,kickoffAt:new Date("2026-11-01T19:00Z")}});
 await assert.rejects(changeCupEntry({cupId:cup.id,teamId:a.id,actorId:admin.id,remove:true,confirmed:true}),/cup fixture/);
 await prisma.fixture.delete({where:{id:f.id}});
 await changeCupEntry({cupId:cup.id,teamId:a.id,actorId:admin.id,remove:true,confirmed:true});
 assert.ok((await previewCupInvitations({cupId:cup.id,actorId:admin.id,teamIds:[a.id],kind:"INITIAL"})).teams[0].error);
 console.log("PASS reminder deduplication and cancellation, explicit entrants, draw protection and no payment changes");
 // Deliberate queue failure must roll back invitation/message creation, not leave a phantom invite.
 const z=await team("Rollback"),zp=await previewCupInvitations({cupId:cup.id,actorId:admin.id,teamIds:[z.id],kind:"INITIAL"});
 await prisma.$executeRawUnsafe(`CREATE FUNCTION cup_test_failure() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW."sourceType"='CUP_INTEREST_INVITATION' THEN RAISE EXCEPTION 'test failure'; END IF; RETURN NEW; END $$`);
 await prisma.$executeRawUnsafe('CREATE TRIGGER cup_test_failure BEFORE INSERT ON "NotificationDispatch" FOR EACH ROW EXECUTE FUNCTION cup_test_failure()');
 const zr=await sendCupInvitations({...sendInput,teamIds:[z.id],previewKey:zp.previewKey});assert.ok(zr[0].error);assert.equal(await loadInvitation(cup.id,z.id),null);
 await prisma.$executeRawUnsafe('DROP TRIGGER cup_test_failure ON "NotificationDispatch"');await prisma.$executeRawUnsafe('DROP FUNCTION cup_test_failure()');
 const templ=await prisma.notificationTemplate.findUniqueOrThrow({where:{key:"cup-interest-invitation"}});
 await prisma.notificationTemplate.update({where:{key:templ.key},data:{body:templ.body+"\nEdited by admin"}});
 const seed=fs.readFileSync('prisma/migrations/20260913001000_cup_invitations/migration.sql','utf8').split('INSERT INTO "NotificationTemplate"')[1];
 await prisma.$executeRawUnsafe('INSERT INTO "NotificationTemplate"'+seed);
 assert.match((await prisma.notificationTemplate.findUniqueOrThrow({where:{key:templ.key}})).body,/Edited by admin/);
 assert.equal(await prisma.notificationDispatch.count({where:{channel:"SMS"}}),0);
 console.log("PASS transaction rollback and editable template preservation; no external provider was called");
}
main().finally(()=>prisma.$disconnect()).catch(error=>{console.error(error);process.exitCode=1;});
