ALTER TABLE "FixtureAiPrediction"
  ADD COLUMN IF NOT EXISTS "modelVersion" TEXT;

-- Existing scheduled predictions were generated by an earlier model. Leaving
-- modelVersion NULL deliberately makes the normal prediction-integrity cron
-- rebuild them with the opponent-adjusted Poisson model after deployment.
