'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
type Props={leagueId:string;date:string;digest:string;canFinalise:boolean;nightId:string|null;missing:number};
export default function VeoNightControls(p:Props){
 const router=useRouter();const[busy,setBusy]=useState(false),[reviewed,setReviewed]=useState(false),[message,setMessage]=useState('');
 async function save(action:string){if(busy)return;setBusy(true);try{const r=await fetch('/api/admin/veo/night',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...p,action,reviewed})});const d=await r.json();setMessage(d.message||d.error);router.refresh();}catch{setMessage('Could not confirm the result. Refresh and check before retrying.');}finally{setBusy(false);}}
 return <div className="space-y-3">{!p.nightId&&<><p className="text-sm leading-6 text-amber-100">{p.missing} team attendance confirmations are still outstanding. Only confirmed teams with a paid request receive a Veo charge.</p><label className="flex items-start gap-3 text-sm leading-6"><input type="checkbox" checked={reviewed} onChange={e=>setReviewed(e.target.checked)} disabled={busy} className="mt-1 h-5 w-5"/>I have reviewed all divisions/leagues sharing this camera tonight. Finalise these pitches and create the shown £5 team add-ons.</label><button type="button" onClick={()=>save('finalise')} disabled={!reviewed||busy||!p.canFinalise} className="min-h-11 rounded-xl bg-fuchsia-500/20 px-5 py-3 font-semibold disabled:opacity-50">{busy?'Saving…':'Finalise Veo bookings'}</button></>}{p.nightId&&<button type="button" onClick={()=>save('notify')} disabled={busy} className="min-h-11 rounded-xl border border-white/20 px-4 py-2">Retry booking updates</button>}{message&&<p role="status" className="rounded-xl border border-white/20 p-3 text-sm leading-6">{message}</p>}</div>;
}
export function VeoRecordingFailure({fixtureId,leagueId}:{fixtureId:string;leagueId:string}){
 const router=useRouter();const[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 async function save(){if(busy)return;setBusy(true);try{const r=await fetch('/api/admin/veo/night',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'fail',fixtureId,leagueId,reason})});const d=await r.json();setMessage(d.message||d.error);router.refresh();}catch{setMessage('Could not confirm the result. Refresh and check before retrying.');}finally{setBusy(false);}}
 return <details className="space-y-3"><summary className="cursor-pointer text-sm text-amber-100">Recording unavailable / return Veo charge</summary><p className="text-xs leading-5 text-white/70">Cancels only the separate Veo add-ons and returns actual payments as team credit. Original match fees and receipts remain untouched.</p><label className="block text-sm">Reason<input value={reason} onChange={e=>setReason(e.target.value)} maxLength={1000} disabled={busy} className="mt-2 min-h-11 w-full rounded-xl border border-white/20 bg-black/30 px-3 py-2"/></label><button type="button" disabled={busy||reason.trim().length<5} onClick={save} className="min-h-11 rounded-xl border border-amber-300/30 px-4 py-2 disabled:opacity-50">{busy?'Saving…':'Cancel Veo add-ons / credit payments'}</button>{message&&<p role="status" className="text-sm">{message}</p>}</details>;
}
