import Link from "next/link";
import { requireAdmin } from "@/lib/requireAdmin";
import { loadCup } from "@/lib/cups/invitation-data";
import { prisma } from "@/lib/prisma";
import { cupDate } from "@/lib/cups/invitation-policy";
export default async function CupDrawPage({params}:{params:Promise<{id:string}>}) {
  await requireAdmin();const {id}=await params;await loadCup(id);
  const fixtures=await prisma.fixture.findMany({where:{leagueId:id},include:{homeTeam:{select:{name:true}},awayTeam:{select:{name:true}},result:true,venue:{select:{name:true}}},orderBy:[{round:"asc"},{kickoffAt:"asc"}]});
  return <div className="space-y-5"><nav aria-label="Cup entrants views" className="flex flex-wrap gap-3 text-sm"><Link href={`/admin/cups/${id}/entrants`} className="rounded-xl border border-white/15 px-4 py-3">Entrants</Link><Link aria-current="page" href={`/admin/cups/${id}/entrants/draw`} className="rounded-xl bg-emerald-400/15 px-4 py-3 text-emerald-100">Draw & rounds</Link></nav>
    <h2 className="text-xl font-semibold">Draw & rounds</h2>
    {!fixtures.length?<section className="space-y-3 rounded-2xl border border-dashed border-white/20 p-6"><h3 className="font-semibold">Draw not created yet</h3><p className="text-sm leading-6 text-white/60">Collect responses and confirm entrants first. Recorded cup fixtures and results will appear here. Automatic knockout draw generation and bracket progression are a separate next stage; no draw has been generated by inviting or adding teams.</p></section>:<><p className="text-sm text-white/60">Recorded cup fixtures, grouped by their saved round. This view does not generate ties or infer progression.</p>{[...new Set(fixtures.map(f=>f.round))].map(round=><section key={round??"unassigned"} className="space-y-3"><h3 className="font-semibold">{round?`Round ${round}`:"Round not assigned"}</h3>{fixtures.filter(f=>f.round===round).map(f=><article key={f.id} className="rounded-xl border border-white/15 p-4"><p className="font-semibold">{f.homeTeam.name} {f.result?`${f.result.homeScore}–${f.result.awayScore}`:"v"} {f.awayTeam.name}</p><p className="mt-2 text-xs text-white/55">{cupDate(f.kickoffAt)} · {f.venue?.name||"Venue to be confirmed"} · {f.status} · {f.publishedAt?"Published":"Draft fixture"}</p><Link href={`/admin/fixtures/${f.id}/result`} className="mt-3 inline-block text-sm text-emerald-300 underline">View result</Link></article>)}</section>)}</>}
  </div>;
}
