import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {writeFileSync,mkdirSync} from 'node:fs';
import {prisma} from '../../src/lib/prisma';
import {readVeoSettings,prepareVeoPublication,londonVeoDate} from '../../src/lib/veo/service';
import {readFixtureVeoOffer,confirmCaptainAttendance,saveFixtureVeoChoice,stopFutureVeoPriority,previewFixtureVeoNight,finaliseFixtureVeoNight,setVeoRecordingOutcome} from '../../src/lib/veo/fixture-bookings';
import {VEO_FIXTURE_TERMS,type VeoFixtureChoice} from '../../src/lib/veo/fixture-choice';
const url=new URL(process.env.DATABASE_URL!);
assert.equal(process.env.VEO_TEST_DATABASE,'1');assert.ok(['localhost','127.0.0.1'].includes(url.hostname));assert.equal(url.pathname,'/sixfl_veo_test');
const prefix=`veo-fix-${randomUUID()}`;const id=(s:string)=>`${prefix}-${s}`;
let passed=0;const pass=(s:string)=>console.log(`PASS ${++passed}: ${s}`);
async function main(){
 const venue=await prisma.venue.create({data:{id:id('venue'),name:'Shared camera venue'},select:{id:true}});
 const leagues:string[]=[];for(let i=0;i<2;i++){const l=await prisma.league.create({data:{id:id(`league${i}`),name:`Camera league ${i}`,slug:id(`slug${i}`)},select:{id:true}});leagues.push(l.id);await prisma.$executeRaw`INSERT INTO "VeoLeagueSettings" ("leagueId",enabled,pitch,"venueId","maxMatches") VALUES (${l.id},true,'1',${venue.id},3)`;}
 const admin=await prisma.user.create({data:{id:id('admin'),email:`${prefix}-admin@example.invalid`,role:'ADMIN'},select:{id:true}});
 const players:string[]=[];const teams:string[]=[];
 for(let i=0;i<12;i++){const l=leagues[Math.floor(i/2)%2];const t=await prisma.team.create({data:{id:id(`team${i}`),name:`Confirmation team ${i}`,claimCode:id(`claim${i}`),leagueId:l,standardMatchFeePence:4000},select:{id:true}});teams.push(t.id);const u=await prisma.user.create({data:{id:id(`captain${i}`),email:`${prefix}-${i}@example.invalid`},select:{id:true}});players.push(u.id);await prisma.teamMember.create({data:{teamId:t.id,userId:u.id,role:'CAPTAIN'}});}
 const fixtures:string[]=[];const start=new Date(Date.now()+7*86400000);start.setUTCHours(17,0,0,0);const date=londonVeoDate(start);
 for(let i=0;i<6;i++){const f=await prisma.fixture.create({data:{id:id(`fixture${i}`),leagueId:leagues[i%2],venueId:venue.id,pitch:String(i%2+1),homeTeamId:teams[2*i],awayTeamId:teams[2*i+1],kickoffAt:new Date(+start+Math.floor(i/2)*2400000),publishedAt:new Date(),matchFeePence:4000,homeMatchFeePence:4000,awayMatchFeePence:4000},select:{id:true}});fixtures.push(f.id);}
 const baseCharge=await prisma.paymentCharge.create({data:{id:id('basecharge'),teamId:teams[4],fixtureId:fixtures[2],leagueId:leagues[0],title:'Already paid match',amountPence:4000,status:'PAID'},select:{id:true}});
 await prisma.paymentTransaction.create({data:{id:id('basepayment'),teamId:teams[4],chargeId:baseCharge.id,amountPence:4000,method:'CASH',paidAt:new Date()}});
 const baseBefore=await prisma.paymentCharge.findUnique({where:{id:baseCharge.id},include:{transactions:true}});
 const schedules=await prisma.fixture.findMany({where:{id:{in:fixtures}},orderBy:{id:'asc'},select:{id:true,homeTeamId:true,awayTeamId:true,kickoffAt:true,homeMatchFeePence:true,awayMatchFeePence:true}});
 assert.equal((await readVeoSettings(leagues[0])).confirmAtFixture,true);
 await prisma.$transaction(tx=>prepareVeoPublication(tx,{leagueId:leagues[0]}));
 assert.equal((await prisma.$queryRaw<any[]>`SELECT * FROM "VeoFixtureSnapshot" WHERE "leagueId"=${leagues[0]}`).length,0);
 pass('default confirmation mode creates no price/allocation snapshot during publication');
 const choice=async(n:number,value:VeoFixtureChoice)=>{const fixtureId=fixtures[Math.floor(n/2)];const offer=await readFixtureVeoOffer(fixtureId,teams[n]);assert.ok(offer?.available);return saveFixtureVeoChoice({fixtureId,teamId:teams[n],actorId:players[n],choice:value,termsVersion:VEO_FIXTURE_TERMS,version:offer.version});};
 assert.equal((await readFixtureVeoOffer(fixtures[0],teams[0]))?.defaultChoice,'NONE');
 await assert.rejects(choice(0,'MATCH'),/Confirm your team/);
 await assert.rejects(confirmCaptainAttendance(fixtures[0],teams[0],players[1]),/active captain/);
 await assert.rejects(confirmCaptainAttendance(fixtures[0],teams[0],admin.id),/active captain/);
 await assert.rejects(confirmCaptainAttendance(fixtures[0],teams[2],players[2]),/not available/);
 pass('no opt-in by default; missing confirmation, wrong team, another captain and admins refused');
 for(let i=0;i<12;i++)await confirmCaptainAttendance(fixtures[Math.floor(i/2)],teams[i],players[i]);
 const offer=await readFixtureVeoOffer(fixtures[0],teams[0]);assert.ok(offer);
 await Promise.all([1,2].map(()=>saveFixtureVeoChoice({fixtureId:fixtures[0],teamId:teams[0],actorId:players[0],choice:'MATCH',termsVersion:VEO_FIXTURE_TERMS,version:offer!.version})));
 assert.equal((await prisma.$queryRaw<any[]>`SELECT * FROM "VeoFixtureRequest" WHERE "fixtureId"=${fixtures[0]} AND "teamId"=${teams[0]}`).length,1);
 await choice(2,'ONGOING');await choice(3,'MATCH');await choice(4,'MATCH');await choice(5,'MATCH');await choice(6,'MATCH');await choice(8,'MATCH');await choice(10,'MATCH');
 assert.equal((await readFixtureVeoOffer(fixtures[1],teams[2]))?.preference,true);
 await choice(2,'NONE');assert.equal((await readFixtureVeoOffer(fixtures[1],teams[2]))?.preference,true);await choice(2,'ONGOING');
 pass('duplicate submissions deduplicate; one-match and ongoing choices coexist; skipping one preserves preference');
 const preview=await previewFixtureVeoNight(leagues[0],date);assert.equal(preview.fixtures.length,6);assert.equal(preview.choices.length,3);
 assert.deepEqual(new Set(preview.choices.map(x=>x.fixtureId)),new Set([fixtures[1],fixtures[2],fixtures[4]]));
 assert.equal((await previewFixtureVeoNight(leagues[1],date)).settings.maxMatches,3);
 await assert.rejects(finaliseFixtureVeoNight(leagues[0],date,players[0],preview.fingerprint),/Administrator/);
 await assert.rejects(finaliseFixtureVeoNight(leagues[0],date,admin.id,'stale'),/changed/);
 const chargesBefore=await prisma.paymentCharge.count();
 assert.equal(await finaliseFixtureVeoNight(leagues[0],date,admin.id,preview.fingerprint),3);
 assert.equal(await prisma.paymentCharge.count(),chargesBefore);
 assert.deepEqual(await prisma.fixture.findMany({where:{id:{in:fixtures}},orderBy:{id:'asc'},select:{id:true,homeTeamId:true,awayTeamId:true,kickoffAt:true,homeMatchFeePence:true,awayMatchFeePence:true}}),schedules);
 assert.deepEqual(await prisma.paymentCharge.findUnique({where:{id:baseCharge.id},include:{transactions:true}}),baseBefore);
 await assert.rejects(finaliseFixtureVeoNight(leagues[1],date,admin.id,preview.fingerprint),/changed/);
 assert.equal((await previewFixtureVeoNight(leagues[1],date)).choices.length,0);
 pass('three slots shared across both leagues; pitch swaps only; stale/double finalisation cannot change paid fees or create duplicate bookings');
 assert.equal((await readFixtureVeoOffer(fixtures[0],teams[0]))?.requestStatus,'UNAVAILABLE');
 assert.equal((await readFixtureVeoOffer(fixtures[1],teams[2]))?.requestStatus,'ACCEPTED');
 await stopFutureVeoPriority(teams[2],leagues[1],players[2]);assert.equal((await readFixtureVeoOffer(fixtures[1],teams[2]))?.preference,false);
 assert.equal((await readFixtureVeoOffer(fixtures[1],teams[2]))?.requestStatus,'ACCEPTED');
 await assert.rejects(prisma.fixture.update({where:{id:fixtures[1]},data:{pitch:'99'}}),/Cancel the accepted Veo/);
 pass('turning off future preference preserves accepted bookings; booked identity/pitch cannot change silently');
 await assert.rejects(setVeoRecordingOutcome({leagueId:leagues[0],fixtureId:fixtures[2],actorId:admin.id,outcome:'READY',videoUrl:'https://youtu.be/test',note:'Usable footage checked'}),/completed/);
 await setVeoRecordingOutcome({leagueId:leagues[1],fixtureId:fixtures[1],actorId:admin.id,outcome:'FAILED',note:'Camera recording failed.'});assert.equal(await prisma.paymentCharge.count(),chargesBefore);
 pass('no pre-match billing; a failed recording before billing creates no charge or credit');
 await prisma.fixture.update({where:{id:fixtures[2]},data:{status:'COMPLETED'}});
 const now=Date.now;Date.now=()=>now()+14*86400000;
 try{
   const input={leagueId:leagues[0],fixtureId:fixtures[2],actorId:admin.id,outcome:'READY' as const,videoUrl:'https://youtu.be/veo-real-test',note:'Usable recording checked by test admin'};
   // Reject the second team charge to prove the first charge and link roll back too.
   await prisma.$executeRawUnsafe(`ALTER TABLE "PaymentCharge" ADD CONSTRAINT veo_test_rollback CHECK ("teamId" <> '${teams[5]}' OR "amountPence" <> 500)`);
   await assert.rejects(setVeoRecordingOutcome(input));
   assert.equal(await prisma.paymentCharge.count(),chargesBefore);assert.equal((await readFixtureVeoOffer(fixtures[2],teams[4]))?.bookingState,'PLANNED');
   await prisma.$executeRawUnsafe('ALTER TABLE "PaymentCharge" DROP CONSTRAINT veo_test_rollback');
   await Promise.all([setVeoRecordingOutcome(input),setVeoRecordingOutcome(input)]);
 }finally{Date.now=now;}
 const requests=await prisma.$queryRaw<{teamId:string;chargeId:string}[]>`SELECT "teamId","chargeId" FROM "VeoFixtureRequest" WHERE "fixtureId"=${fixtures[2]} ORDER BY "teamId"`;
 assert.equal(requests.length,2);assert.ok(requests.every(x=>x.chargeId));assert.equal(await prisma.paymentCharge.count(),chargesBefore+2);
 const standalone=await prisma.paymentCharge.findMany({where:{id:{in:requests.map(r=>r.chargeId)}}});assert.ok(standalone.every(c=>c.amountPence===500&&c.fixtureId===null&&c.latePaymentFeeStatus==='WAIVED'));
 pass('recording billing rolls back atomically on failure; concurrent completion creates one standalone £5 per accepted team');
 await prisma.paymentTransaction.create({data:{id:id('veopay1'),chargeId:requests[0].chargeId,teamId:requests[0].teamId,amountPence:500,method:'CASH',paidAt:new Date()}});
 await prisma.paymentTransaction.create({data:{id:id('veopay2'),chargeId:requests[1].chargeId,teamId:requests[1].teamId,amountPence:200,method:'CASH',paidAt:new Date()}});
 await setVeoRecordingOutcome({leagueId:leagues[0],fixtureId:fixtures[2],actorId:admin.id,outcome:'FAILED',note:'Footage unusable after review'});
 let credit=await prisma.$queryRaw<{amountPence:number}[]>`SELECT "amountPence" FROM "TeamCreditLedgerEntry" WHERE id IN (${`tcred_veo_cancel_${requests[0].chargeId}`},${`tcred_veo_cancel_${requests[1].chargeId}`}) ORDER BY "amountPence"`;
 assert.deepEqual(credit.map(c=>c.amountPence),[200,500]);
 await prisma.paymentTransaction.create({data:{id:id('late-receipt'),chargeId:requests[1].chargeId,teamId:requests[1].teamId,amountPence:100,method:'STRIPE',paidAt:new Date(),stripeCheckoutSessionId:id('late-session')}});
 await prisma.paymentCharge.update({where:{id:requests[1].chargeId},data:{status:'PAID'}});
 assert.equal((await prisma.paymentCharge.findUnique({where:{id:requests[1].chargeId}}))?.status,'VOID');
 assert.equal((await prisma.$queryRaw<any[]>`SELECT "amountPence" FROM "TeamCreditLedgerEntry" WHERE id=${`tcred_veo_cancel_${requests[1].chargeId}`}`)[0].amountPence,300);
 await prisma.paymentTransaction.delete({where:{id:id('late-receipt')}});
 assert.equal((await prisma.$queryRaw<any[]>`SELECT "amountPence" FROM "TeamCreditLedgerEntry" WHERE id=${`tcred_veo_cancel_${requests[1].chargeId}`}`)[0].amountPence,200);
 assert.deepEqual(await prisma.paymentCharge.findUnique({where:{id:baseCharge.id},include:{transactions:true}}),baseBefore);
 pass('failed paid footage voids only the add-on and credits real receipts; late receipts/reversals stay correct and cannot reopen billing');
 await prisma.fixture.update({where:{id:fixtures[4]},data:{status:'CANCELLED'}});
 assert.equal((await readFixtureVeoOffer(fixtures[4],teams[8]))?.bookingState,'CANCELLED');
 pass('normal fixture cancellation cancels optional filming without blocking fixture operations');
 mkdirSync('artifacts/veo',{recursive:true});writeFileSync('artifacts/veo/fixture-booking-results.json',JSON.stringify({passed,date,leagues,fixtureIds:fixtures}));
 console.log(`${passed} fixture booking integration checks passed.`);
}
main().finally(()=>prisma.$disconnect());
